name: Build and Deploy Quiz Site

# Trigger the workflow
on:
  push:
    branches: [ main, master ]  # Runs when you push to main or master branch
  pull_request:
    branches: [ main, master ]  # Runs on pull requests
  workflow_dispatch:            # Allows manual triggering from GitHub UI

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Get your code from GitHub
    - name: Checkout repository
      uses: actions/checkout@v4
      
    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'
        
    # Step 3: Cache pip dependencies (speeds up future builds)
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    # Step 4: Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
                
    # Step 5: Build the static site
    - name: Build site
      run: |
        echo "Building static site..."
        python build.py
        echo "Build completed!"
        
    # Step 6: List generated files (for debugging)
    - name: List build output
      run: |
        echo "Generated files:"
        ls -la dist/
        
    # Step 7: Deploy to Cloudflare Pages
    - name: Deploy to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: cardiac-lab  # Change this to your Cloudflare Pages project name
        directory: dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
